#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

case "$DISTRO_NAME" in
  'ubuntu'|'debian')
    add-apt-repository ppa:openjdk-r/ppa
    apt-get update
    apt-get install -y openjdk-8-jdk
    update-java-alternatives --list
    ;;
  'fedora'|'centos'|'centos7'|'opensuse')
    yum install -y default-jdk
    ;;
esac
