#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [[ $DISTRO_NAME = "ubuntu" || $DISTRO_NAME = "debian" ]]; then
    add-apt-repository ppa:openjdk-r/ppa
    apt-get update
    apt-get install -y openjdk-8-jdk
    update-java-alternatives --list || /bin/true
else
    yum install -y default-jdk
fi
