#!/bin/bash
if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

[ -n "$TARGET_ROOT" ]

if [ 'trusty' == $DIB_RELEASE ]; then
    echo FSCKFIX=yes > $TARGET_ROOT/etc/default/rcS
fi